### ISSUE TITLE
Move source backup content to common

### ISSUE THREAD

**Issue by minhkhul** [cmu-delphi/covidcast-indicators#2089]
**Context**

I think for next release maybe also change where the raw files are saved; maybe /common/indicator/<data_source>?

_Originally posted by @aysim319 in https://github.com/cmu-delphi/covidcast-indicators/pull/2000#discussion_r1888869042_

The current backup dir setup is placing sour backup files into a location super inconvenient for patching, so let's move it.

**Todo**

- [x] make dir on prod in common using automation + give appropriate permissions
- [x] PR to change to ansible template params.json + adjust local template accordingly
- [ ] BEFORE RELEASE: move old backup files from current place to new dir setup.
