### ISSUE TITLE
Checklist for un-publishing ChangeHC, just in case

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#518]
If we can't get a Terms of Use update done before the end of day, we'll be removing public access to Change. Here's what needs to happen if that's the case:

- [x] Postpone [next Automation run](https://delphi.midas.cs.cmu.edu/~automation/task_edit.php?id=47) to next week
- [x] Run `UPDATE covidcast SET source="changehc_[some random hash]", is_wip=1 WHERE source="changehc"` in primary
- [x] Merge [PR to unpublish from the API docs](https://github.com/cmu-delphi/delphi-epidata/pull/285)
- [x] Send whoops notification to mailing list

**Comment by krivard** [comment]
Notification sent ~6pm.
