### ISSUE TITLE
Checklist for re-publishing Change Healthcare signals

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#525]
- [x] Merge [source name PR](https://github.com/cmu-delphi/covidcast-indicators/pull/524)
- [x] [Deploy to production](https://github.com/cmu-delphi/covidcast-indicators/pull/551)
- [x] Edit docs to reflect new source name
- [x] Edit docs to include new TOU
- [x] Run `UPDATE covidcast SET source="chng", is_wip=0 WHERE source="changehc_[random hash]"` in primary
- [x] Reactivate [chc job in Automation](https://delphi.midas.cs.cmu.edu/~automation/task_edit.php?id=47)

**Comment by krivard** [comment]
Fin
